#-------------------------------
# General Site Settings
title: Hamthoven's Archive
logo: favicon.ico # You can add own logo.
description: 햄또븐의 개발 블로그


#-------------------------------
# Author Settings
author:
  name: Yujin Kang
  image: 01.jpg
  say-hello: Hello, I’m <strong>Yujin Kang</strong></br> <strong>(a.k.a. Hamthoven)</strong>
  bio: I love to develope mobile applications and playing with data.


#-------------------------------
# Contact links
twitter: https://github.com/Hamthoven # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle

#  dribbble: https://dribbble.com/ # Add your Dribbble handle
#  instagram: https://instagram.com/ # Add your Instagram handle
#  pinterest: https://pinterest.com/ # Add your Pinterest handle

#-------------------------------
# Comment Section (Disqus)
#disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
