#-------------------------------
# General Site Settings
title: Zolan
logo: logo.svg # You can add own logo.
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Yujin Kang
  image: 01.jpg
  say-hello: Hello, Iâ€™m <strong>Yujin Kang (a.k.a. Hamthoven).</strong>
  bio: I love to develope mobile applications and playing with data.


#-------------------------------
# Contact links
github: https://github.com/Hamthoven/ # Github handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
